modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="baubles_example"
version="${mod_version}"
displayName="Baubles 2 Example"
authors="${mod_authors}"
description='''${mod_description}'''
credits='''${mod_credits}'''

[[dependencies."baubles_example"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."baubles_example"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."baubles_example"]]
modId="baubles"
type="required"
versionRange="[0.1]"
ordering="NONE"
side="BOTH"
